def bubblesort(list):
    for i in range(len(list)):  # O(n)
        swapped = False  # O(1)
        for j in range(len(list)-i-1):  # O(n)
            if int(list[j]) > int(list[j+1]):  # O(1)
                list[j], list[j+1] = list[j+1], list[j]  # O(1)
                swapped = True  # O(1)
        if not swapped:  # O(1)
            break  # O(1)
    return list  # O(1)
