def shellsort(list):
    interval = len(list) // 2  # O(1)
    while interval > 0:  # O(log n)
        for i in range(interval, len(list)):  # O(n)
            temp = int(list[i])  # O(1)
            j = i  # O(1)
            while j >= interval and int(list[j - interval]) > temp:  # O(n)
                list[j] = list[j - interval]  # O(1)
                j -= interval  # O(1)
            list[j] = temp  # O(1)
        interval = interval // 2  # O(1)
    return list  # O(1)
